Catalogs:
 - Name: personal
   # in Kilobytes
   CksumKBytes: 0
   IndexJobCount: 10
   ResultJobCount: 10
   IndexPaths:

   - Path: c:\opencv
     Exclude: 
       - "*.tgz"
   - Path: d:\google drive
     Exclude: 
       - "*.csv"

   - Path: D:\data\projects\python
   - Path: C:\Windows
Database:
  ConnectionString: "postgresql://pgadmin:Boom123@bigbox.home.mpa:6321/FileScan"
  # ConnectionString: "postgresql://crate@cratedb.service.home.mpa:5432/doc"
   