Catalogs:
 - Name: personal
   # in Kilobytes
   CksumKBytes: 0
   IndexJobCount: 10
   ResultJobCount: 10
   IndexPaths:

   - Path: c:\opencv
     Exclude: 
       - "*.tgz"
   - Path: d:\google drive
     Exclude: 
       - "*.csv"

   - Path: D:\data\projects\python
   - Path: C:\Windows
Database:
  ConnectionString: ""
   