Catalogs:
 - Name: personal
   # in Kilobytes
   CksumKBytes: 4
   IndexJobCount: 5
   ResultJobCount: 5
   IndexPaths:

   - Path: c:\opencv
     Exclude: 
       - "*.tgz"
   - Path: d:\google drive
     Exclude: 
       - "*.csv"

   - Path: D:\data\projects\python
   